# Generated by Django 3.0.6 on 2020-05-29 17:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('imagesapp', '0003_delete_dosya_havuz'),
        ('bulut', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='kullanici',
        ),
    ]
