# Generated by Django 3.0.6 on 2020-05-29 19:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bulut', '0003_kullanici'),
    ]

    operations = [
        migrations.AlterField(
            model_name='kullanici',
            name='kAd',
            field=models.CharField(db_column='Adı', max_length=50, null=True, verbose_name='Adı'),
        ),
        migrations.AlterField(
            model_name='kullanici',
            name='kSoyad',
            field=models.CharField(db_column='Soyadı', max_length=50, null=True, verbose_name='Soyadı'),
        ),
    ]
