# Generated by Django 3.0.6 on 2020-05-29 23:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('imagesapp', '0007_delete_dosya_havuz'),
        ('bulut', '0004_auto_20200529_2217'),
    ]

    operations = [
        migrations.DeleteModel(
            name='kullanici',
        ),
    ]
