# Generated by Django 3.0.6 on 2020-05-29 23:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bulut', '0006_kullanici'),
    ]

    operations = [
        migrations.RenameField(
            model_name='kullanici',
            old_name='id',
            new_name='kId',
        ),
        migrations.RenameField(
            model_name='kullanici',
            old_name='klAdı',
            new_name='kadi',
        ),
    ]
