# Generated by Django 3.0.6 on 2020-05-29 23:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bulut', '0007_auto_20200530_0230'),
    ]

    operations = [
        migrations.RenameField(
            model_name='kullanici',
            old_name='Ad',
            new_name='adi',
        ),
        migrations.RenameField(
            model_name='kullanici',
            old_name='Bolum',
            new_name='bolum',
        ),
        migrations.RenameField(
            model_name='kullanici',
            old_name='kId',
            new_name='id',
        ),
        migrations.RenameField(
            model_name='kullanici',
            old_name='kadi',
            new_name='kAd',
        ),
        migrations.RenameField(
            model_name='kullanici',
            old_name='Mail',
            new_name='mail',
        ),
        migrations.RenameField(
            model_name='kullanici',
            old_name='OgrNo',
            new_name='ogrNo',
        ),
        migrations.RenameField(
            model_name='kullanici',
            old_name='Okul',
            new_name='okul',
        ),
        migrations.RenameField(
            model_name='kullanici',
            old_name='Soyad',
            new_name='soyadi',
        ),
    ]
