# Generated by Django 3.0.6 on 2020-05-28 20:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='file_storage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file_name', models.CharField(db_column='Dosya Adı', max_length=255, verbose_name='Dosya Adı')),
                ('file_url', models.TextField(db_column='Dosya URL', verbose_name='Dosya URL')),
                ('last_update', models.DateTimeField(auto_now=True, db_column='Son Güncelleme', verbose_name='Son Güncelleme')),
            ],
        ),
    ]
