# Generated by Django 3.0.6 on 2020-05-29 17:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bulut', '0001_initial'),
        ('imagesapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='dosya_havuz',
            fields=[
                ('dId', models.AutoField(db_column='Dosya ID', primary_key=True, serialize=False, verbose_name='Dosya ID')),
                ('dersAdı', models.CharField(db_column='Ders Adı', max_length=255, verbose_name='Ders Adı')),
                ('aciklama', models.CharField(db_column='Açıklama', max_length=255, verbose_name='Açıklama')),
                ('file_name', models.CharField(db_column='Dosya Adı', max_length=255, verbose_name='Dosya Adı')),
                ('file_url', models.TextField(db_column='Dosya URL', verbose_name='Dosya URL')),
                ('last_update', models.DateTimeField(auto_now=True, db_column='Son Güncelleme', verbose_name='Son Güncelleme')),
                ('kId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bulut.kullanici')),
            ],
        ),
    ]
