# Generated by Django 3.0.6 on 2020-05-29 23:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('imagesapp', '0004_dosya_havuz'),
    ]

    operations = [
        migrations.AddField(
            model_name='dosya_havuz',
            name='kOgrNo',
            field=models.CharField(db_column='Öğrenci No', max_length=255, null=True, verbose_name='Öğrenci No'),
        ),
    ]
