# Generated by Django 3.0.6 on 2020-05-29 23:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('imagesapp', '0005_dosya_havuz_kogrno'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dosya_havuz',
            name='aciklama',
            field=models.CharField(db_column='Açıklama', max_length=255, null=True, verbose_name='Açıklama'),
        ),
    ]
