# Generated by Django 3.0.6 on 2020-05-29 23:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('imagesapp', '0006_auto_20200530_0211'),
    ]

    operations = [
        migrations.DeleteModel(
            name='dosya_havuz',
        ),
    ]
