# Generated by Django 3.0.6 on 2020-05-29 23:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('imagesapp', '0008_dosya_havuz'),
    ]

    operations = [
        migrations.DeleteModel(
            name='dosya_havuz',
        ),
    ]
