# Generated by Django 3.0.6 on 2020-05-31 09:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('imagesapp', '0010_dosya_havuz'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dosya_havuz',
            name='file_name',
            field=models.CharField(db_column='Adı', max_length=255, verbose_name='Adı'),
        ),
    ]
