# Generated by Django 3.0.6 on 2020-05-31 09:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('imagesapp', '0011_auto_20200531_1217'),
    ]

    operations = [
        migrations.AddField(
            model_name='dosya_havuz',
            name='dosyaAdı',
            field=models.CharField(db_column='Dosya Adı', max_length=255, null=True, verbose_name='Dosya Adı'),
        ),
        migrations.AddField(
            model_name='dosya_havuz',
            name='olusturma',
            field=models.DateTimeField(auto_now_add=True, db_column='Oluşturma Tarihi', null=True, verbose_name='Oluşturma Tarihi'),
        ),
    ]
