# Generated by Django 3.0.6 on 2020-05-31 09:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('imagesapp', '0012_auto_20200531_1221'),
    ]

    operations = [
        migrations.DeleteModel(
            name='file_storage',
        ),
    ]
